language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - ruby-head
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y tidy
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
gemfile: Gemfile
script: bundle exec rspec

